#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

PY="$DIR/.venv/bin/python"
HYPR_DIR="$HOME/.config/hypr"
CUSTOM_LUA="$HYPR_DIR/custom.lua"
HYPRLAND_CONF="$HYPR_DIR/hyprland.conf"
KOTODAMA_CONF="$HYPR_DIR/kotodama.conf"

LUA_BEGIN="-- BEGIN KOTODAMA KEYBINDINGS"
LUA_END="-- END KOTODAMA KEYBINDINGS"
CONF_BEGIN="# BEGIN KOTODAMA KEYBINDINGS"
CONF_END="# END KOTODAMA KEYBINDINGS"

# One source of truth for the binds, rendered into whichever config format the
# running Hyprland actually reads. Fields are :: separated:
#   <modifiers and key> :: <shell command, already quoted> :: <description>
kotodama_binds() {
    cat <<EOF
SUPER, D::"$PY" "$DIR/dictate.py" toggle::Dictation: record / transcribe to clipboard
SUPER, A::"$DIR/screenshot.sh"::Screenshot: annotate and copy
SUPER SHIFT, V::"$DIR/clip-picker.sh"::Browse recent screenshots (clipboard history)
SUPER, R::"$PY" "$DIR/session.py" toggle::Session: start / end (record + screenshot)
SUPER, I::"$PY" "$DIR/session.py" screenshot::Session: add screenshot
SUPER SHIFT, I::"$PY" "$DIR/session.py" split::Session: split transcript segment
SUPER, O::"$PY" "$DIR/session_browser.py"::Session: browse and copy
EOF
}

render_hyprlang() {
    echo "# Auto-generated by install.sh — remove with uninstall.sh, do not edit by hand."
    echo "# Paths are double-quoted so a project directory containing spaces still works."
    echo ""
    local line key rest cmd desc
    while IFS='' read -r line; do
        [ -n "$line" ] || continue
        key="${line%%::*}"; rest="${line#*::}"
        cmd="${rest%%::*}"; desc="${rest#*::}"
        printf 'bind = %s, exec, %s # %s\n' "$key" "$cmd" "$desc"
    done < <(kotodama_binds)
}

render_lua() {
    echo "-- Auto-generated by install.sh — remove with uninstall.sh, do not edit by hand."
    echo "-- Commands use [[ ]] long strings so a project directory containing spaces still works."
    echo ""
    local line key rest cmd desc luakey
    while IFS='' read -r line; do
        [ -n "$line" ] || continue
        key="${line%%::*}"; rest="${line#*::}"
        cmd="${rest%%::*}"; desc="${rest#*::}"
        luakey="$(printf '%s' "$key" | tr -d ',' | tr -s ' ' | sed 's/ / + /g')"
        printf 'hl.bind("%s", hl.dsp.exec_cmd([[%s]]), { description = "%s" })\n' \
            "$luakey" "$cmd" "$desc"
    done < <(kotodama_binds)
}

# Which config format is this Hyprland actually reading? Getting this wrong is silent:
# binds land in a file nothing loads and the installer still reports success.
detect_flavor() {
    local out
    if command -v hyprctl &>/dev/null; then
        out="$(hyprctl eval "return 1" 2>&1 || true)"
        case "$out" in
            *"lua config manager"*) echo hyprlang; return ;;
        esac
        if [ "$(printf '%s' "$out" | tr -d '[:space:]')" = "1" ]; then
            echo lua; return
        fi
    fi
    # Compositor not running, or an answer we don't recognise — go by what's on disk.
    if [ -f "$HYPR_DIR/hyprland.lua" ]; then echo lua
    elif [ -f "$HYPRLAND_CONF" ]; then echo hyprlang
    else echo unknown
    fi
}

strip_block() { # <file> <begin marker> <end marker>
    [ -f "$1" ] || return 0
    # -e and -- are load-bearing: the Lua markers start with "--", which grep and
    # sed would otherwise parse as an option and bail out.
    grep -qF -e "$2" -- "$1" || return 0
    sed -i "\|$2|,\|$3|d" "$1"
}

# Modifier bitmask as reported by `hyprctl binds`: SHIFT=1, CTRL=4, ALT=8, SUPER=64.
modmask_for() {
    local mask=0
    case "$1" in *SUPER*) mask=$((mask + 64)) ;; esac
    case "$1" in *SHIFT*) mask=$((mask + 1)) ;; esac
    echo "$mask"
}

# A bind that silently loses to an existing one looks exactly like a bind that
# never installed, so say which keys are now claimed twice.
check_conflicts() {
    command -v hyprctl &>/dev/null || return 0
    local live pairs line key desc mask k n found=0
    live="$(hyprctl binds 2>/dev/null)" || return 0
    [ -n "$live" ] || return 0
    pairs="$(awk '/modmask:/ { m = $2 } /^[[:space:]]*key:/ { print m, $2 }' <<<"$live")"

    while IFS='' read -r line; do
        [ -n "$line" ] || continue
        key="${line%%::*}"; desc="${line##*::}"
        mask="$(modmask_for "$key")"
        k="${key##*, }"
        n="$(grep -c "^$mask $k\$" <<<"$pairs" || true)"
        if [ "${n:-0}" -gt 1 ]; then
            if [ "$found" -eq 0 ]; then
                echo ""
                echo "NOTE: these keys are now bound more than once — something already in your"
                echo "      Hyprland config claims them too, and both binds will fire:"
                found=1
            fi
            printf '        %-16s kotodama: %s\n' "$key" "$desc"
        fi
    done < <(kotodama_binds)

    [ "$found" -eq 1 ] && echo "      Rebind whichever you care less about."
    return 0
}

command -v pacman >/dev/null || {
    echo "This installer assumes an Arch-based system (pacman not found). Aborting."
    exit 1
}

echo "==> Checking system packages..."
PACKAGES=(grim slurp satty imv wl-clipboard cliphist rofi pipewire libnotify)
TO_INSTALL=()
for pkg in "${PACKAGES[@]}"; do
    pacman -Qi "$pkg" &>/dev/null || TO_INSTALL+=("$pkg")
done

mkdir -p .state
touch .state/installed-packages.txt

if [ "${#TO_INSTALL[@]}" -gt 0 ]; then
    echo "Installing: ${TO_INSTALL[*]}"
    sudo pacman -S --needed --noconfirm "${TO_INSTALL[@]}"
    { cat .state/installed-packages.txt; printf '%s\n' "${TO_INSTALL[@]}"; } \
        | sed '/^$/d' | sort -u > .state/installed-packages.txt.tmp
    mv .state/installed-packages.txt.tmp .state/installed-packages.txt
else
    echo "All required packages already installed."
fi

echo "==> Checking for uv..."
if ! command -v uv &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

echo "==> Setting up Python environment (uv sync)..."
uv sync

echo "==> Setting up .env..."
NEEDS_KEY=1
if [ -f .env ]; then
    echo ".env already exists, leaving it alone."
    grep -q "^GROQ_API_KEY=gsk_" .env 2>/dev/null && NEEDS_KEY=0
else
    cp .env.example .env
    echo "Created .env from .env.example."
fi

echo "==> Wiring up Hyprland keybindings..."
FLAVOR="$(detect_flavor)"
WARN_NEW_LUA=0

case "$FLAVOR" in
lua)
    mkdir -p "$HYPR_DIR"
    # Drop a block left by an install under the other config format, so switching
    # formats doesn't leave dead binds behind in a file nothing reads.
    strip_block "$HYPRLAND_CONF" "$CONF_BEGIN" "$CONF_END"
    rm -f "$KOTODAMA_CONF"
    [ -f "$CUSTOM_LUA" ] || { touch "$CUSTOM_LUA"; WARN_NEW_LUA=1; }
    # Rewrite rather than skip, so re-running after moving the project fixes the paths.
    strip_block "$CUSTOM_LUA" "$LUA_BEGIN" "$LUA_END"
    { echo ""; echo "$LUA_BEGIN"; render_lua; echo "$LUA_END"; } >> "$CUSTOM_LUA"
    echo "Hyprland is using the Lua config manager."
    echo "Wrote binds to $CUSTOM_LUA"
    ;;
hyprlang)
    mkdir -p "$HYPR_DIR"
    strip_block "$CUSTOM_LUA" "$LUA_BEGIN" "$LUA_END"
    { echo "$CONF_BEGIN"; render_hyprlang; echo "$CONF_END"; } > "$KOTODAMA_CONF"
    strip_block "$HYPRLAND_CONF" "$CONF_BEGIN" "$CONF_END"
    { echo ""; echo "$CONF_BEGIN"; echo "source = $KOTODAMA_CONF"; echo "$CONF_END"; } \
        >> "$HYPRLAND_CONF"
    echo "Hyprland is using the classic hyprlang config."
    echo "Wrote binds to $KOTODAMA_CONF, sourced from $HYPRLAND_CONF"
    ;;
*)
    echo "Couldn't tell whether your Hyprland uses the Lua config manager or the"
    echo "classic hyprlang config, so I left your config alone. Add the binds by hand:"
    echo ""
    echo "  hyprlang (~/.config/hypr/hyprland.conf):"
    render_hyprlang | sed 's/^/    /'
    echo ""
    echo "  Lua (~/.config/hypr/custom.lua):"
    render_lua | sed 's/^/    /'
    ;;
esac

if [ "$WARN_NEW_LUA" -eq 1 ]; then
    echo ""
    echo "NOTE: $CUSTOM_LUA didn't exist, so I created it. Make sure your main"
    echo "hyprland.lua actually loads it (e.g. a line like require(\"custom\") —"
    echo "this is how ML4W dotfiles do it). Otherwise these binds won't take effect."
fi

if command -v hyprctl &>/dev/null; then
    hyprctl reload config-only &>/dev/null && echo "Reloaded Hyprland config." || true
fi

if [ "$FLAVOR" != "unknown" ]; then
    check_conflicts
fi

echo ""
echo "==> Install complete."
echo ""
echo "Keybindings: Super+D dictate | Super+A screenshot | Super+Shift+V browse"
echo "clipboard screenshots | Super+R session start/end | Super+I add screenshot |"
echo "Super+Shift+I split transcript | Super+O browse sessions"
echo ""

if [ "$NEEDS_KEY" -eq 1 ]; then
    echo "############################################################"
    echo "#  IMPORTANT: nothing above will work yet.                  #"
    echo "#                                                           #"
    echo "#  You still need a free Groq API key:                     #"
    echo "#    1. https://console.groq.com -> sign up (no card)       #"
    echo "#    2. API Keys (left sidebar) -> Create API Key           #"
    echo "#    3. Edit: $DIR/.env"
    echo "#       Set:  GROQ_API_KEY=gsk_...                          #"
    echo "############################################################"
fi
