#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

MARKER_BEGIN="-- BEGIN KOTODAMA KEYBINDINGS"
MARKER_END="-- END KOTODAMA KEYBINDINGS"

command -v pacman >/dev/null || {
    echo "This installer assumes an Arch-based system (pacman not found). Aborting."
    exit 1
}

echo "==> Checking system packages..."
PACKAGES=(grim slurp satty imv wl-clipboard cliphist rofi pipewire libnotify)
TO_INSTALL=()
for pkg in "${PACKAGES[@]}"; do
    pacman -Qi "$pkg" &>/dev/null || TO_INSTALL+=("$pkg")
done

mkdir -p .state
touch .state/installed-packages.txt

if [ "${#TO_INSTALL[@]}" -gt 0 ]; then
    echo "Installing: ${TO_INSTALL[*]}"
    sudo pacman -S --needed --noconfirm "${TO_INSTALL[@]}"
    { cat .state/installed-packages.txt; printf '%s\n' "${TO_INSTALL[@]}"; } \
        | sed '/^$/d' | sort -u > .state/installed-packages.txt.tmp
    mv .state/installed-packages.txt.tmp .state/installed-packages.txt
else
    echo "All required packages already installed."
fi

echo "==> Checking for uv..."
if ! command -v uv &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

echo "==> Setting up Python environment (uv sync)..."
uv sync

echo "==> Setting up .env..."
NEEDS_KEY=1
if [ -f .env ]; then
    echo ".env already exists, leaving it alone."
    grep -q "^GROQ_API_KEY=gsk_" .env 2>/dev/null && NEEDS_KEY=0
else
    cp .env.example .env
    echo "Created .env from .env.example."
fi

echo "==> Wiring up Hyprland keybindings..."
CUSTOM_LUA="$HOME/.config/hypr/custom.lua"
WARN_NEW_FILE=0
if [ ! -f "$CUSTOM_LUA" ]; then
    mkdir -p "$(dirname "$CUSTOM_LUA")"
    touch "$CUSTOM_LUA"
    WARN_NEW_FILE=1
fi

if grep -q "$MARKER_BEGIN" "$CUSTOM_LUA"; then
    echo "Keybindings already present in $CUSTOM_LUA — skipping (run uninstall.sh first to reset)."
else
    {
        echo ""
        echo "$MARKER_BEGIN"
        echo "-- Auto-generated by install.sh — remove with uninstall.sh, do not edit by hand."
        echo "local mainMod = \"SUPER\""
        echo "local kotodamaDir = \"$DIR\""
        echo "local kotodamaPy = kotodamaDir .. \"/.venv/bin/python\""
        echo ""
        echo 'hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(kotodamaPy .. " " .. kotodamaDir .. "/dictate.py toggle"), { description = "Dictation: record / transcribe to clipboard" })'
        echo 'hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(kotodamaDir .. "/screenshot.sh"), { description = "Screenshot: annotate and copy" })'
        echo 'hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(kotodamaDir .. "/clip-picker.sh"), { description = "Browse recent screenshots (clipboard history)" })'
        echo ""
        echo 'hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(kotodamaPy .. " " .. kotodamaDir .. "/session.py toggle"), { description = "Session: start / end (record + screenshot)" })'
        echo 'hl.bind(mainMod .. " + I", hl.dsp.exec_cmd(kotodamaPy .. " " .. kotodamaDir .. "/session.py screenshot"), { description = "Session: add screenshot" })'
        echo 'hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd(kotodamaPy .. " " .. kotodamaDir .. "/session.py split"), { description = "Session: split transcript segment" })'
        echo 'hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(kotodamaPy .. " " .. kotodamaDir .. "/session_browser.py"), { description = "Session: browse and copy" })'
        echo "$MARKER_END"
    } >> "$CUSTOM_LUA"
    echo "Added keybindings to $CUSTOM_LUA"
fi

if [ "$WARN_NEW_FILE" -eq 1 ]; then
    echo "NOTE: $CUSTOM_LUA didn't exist, so I created it. Make sure your main"
    echo "hyprland.lua actually loads it (e.g. a line like require(\"custom\") —"
    echo "this is how ML4W dotfiles do it). Otherwise these binds won't take effect."
fi

if command -v hyprctl &>/dev/null; then
    hyprctl reload config-only &>/dev/null && echo "Reloaded Hyprland config." || true
fi

echo ""
echo "==> Install complete."
echo ""
echo "Keybindings: Super+D dictate | Super+A screenshot | Super+Shift+V browse"
echo "clipboard screenshots | Super+R session start/end | Super+I add screenshot |"
echo "Super+Shift+I split transcript | Super+O browse sessions"
echo ""

if [ "$NEEDS_KEY" -eq 1 ]; then
    echo "############################################################"
    echo "#  IMPORTANT: nothing above will work yet.                  #"
    echo "#                                                           #"
    echo "#  You still need a free Groq API key:                     #"
    echo "#    1. https://console.groq.com -> sign up (no card)       #"
    echo "#    2. API Keys (left sidebar) -> Create API Key           #"
    echo "#    3. Edit: $DIR/.env"
    echo "#       Set:  GROQ_API_KEY=gsk_...                          #"
    echo "############################################################"
fi
